### PR TITLE
STOR-2017: Bump all deps for 4.18

### PR DESCRIPTION
**Pull request by dobsonj**
This pulls in the revert commit from https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/273 , drops the logging patch in the vendor directory, and bumps openshift/api to get https://github.com/openshift/api/commit/ec9bf3faa1aa2f52805c44b7b13cd7ab4b984241

- **Revert changes in c36125987e97a04b011662cd17045b64f463dee2**
- **Bump openshift/api && go mod tidy && go mod vendor**

/cc @openshift/storage @gnufied @rhrmo

### CODE REVIEW

**Comment by rhrmo** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-upgrade-from-stable-4.17-e2e-vsphere-ovn-upgrade

**Comment by rhrmo** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.18-upgrade-from-stable-4.17-e2e-vsphere-ovn-upgrade

**Comment by dobsonj** [comment]
The last payload test had these three failures:
```
[sig-node] node-lifecycle detects unexpected not ready node expand_more
[sig-node] node-lifecycle detects unreachable state on node expand_more
[bz-apiserver-auth][invariant] alert/PodSecurityViolation should not be at or above info
```
In the previous run, it was just:
```
[bz-apiserver-auth][invariant] alert/PodSecurityViolation should not be at or above info
```
```
Nov 21 21:57:02.641 - 1126s I namespace/openshift-kube-apiserver alert/PodSecurityViolation alertstate/firing severity/info ALERTS{alertname="PodSecurityViolation", alertstate="firing", namespace="openshift-kube-apiserver", ocp_namespace="openshift-catalogd", policy_level="restricted", prometheus="openshift-monitoring/k8s", severity="info"}}
```
So two flakes and one pod security violation in a different namespace.
But most important for this PR, this job passed:
```
[sig-arch] events should not repeat pathologically for ns/openshift-cluster-csi-drivers
```
Which is the thing the openshift/api bump is supposed to fix. I don't see much value in continuing to re-run this test.

/label acknowledge-critical-fixes-only
/label qe-approved

**Comment by dobsonj** [comment]
/override ci/prow/e2e-vsphere-ovn-upgrade
same pod security violation in namespace/openshift-kube-apiserver

**Pull request merged**
