### PR TITLE
Bug 2099864: Reorder static resources to create RBAC first

### PR DESCRIPTION
**Pull request by jsafrane**
The privileged RBAC objects should be created first to make sure the CSI driver Deployment / DaemonSet can use privileged SCC.

cc @openshift/storage 

/hold
for testing

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
/lgtm

IMO we can reorder even if it doesn't completely fix the original issue.

**Comment by jsafrane** [comment]
/hold cancel
no errors seen in 3 tests

**Pull request merged**
