### PR TITLE
[release-4.13] OCPBUGS-28998: Mark the operator as Disabled on connection error

### PR DESCRIPTION
**Pull request by jsafrane**
This is a manual cherry-pick of https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/219 into 4.13.

### CODE REVIEW

**Comment by Phaow** [comment]
/label cherry-pick-approved
/label qe-approved
With the **[bug reproduce steps](https://issues.redhat.com/browse/OCPBUGS-27159?focusedId=23787718&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23787718)**, using the pre merged build, the same reproduce step the issue doesn't happen again, 
pre verify passed on `4.13.0-0.test-2024-02-06-020832-ci-ln-l529zd2-latest` (`build 4.13,openshift/vmware-vsphere-csi-driver-operator#224,openshift/cluster-storage-operator#450`)
```console
$ oc get co/storage -w
NAME      VERSION                                                AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
storage   4.13.0-0.test-2024-02-06-020832-ci-ln-l529zd2-latest   False       True          False      2m11s   VSphereCSIDriverOperatorCRAvailable: Waiting for VSphere operator to report status
storage   4.13.0-0.test-2024-02-06-020832-ci-ln-l529zd2-latest   False       True          False      2m39s   VSphereCSIDriverOperatorCRAvailable: Waiting for VSphere operator to report status
storage   4.13.0-0.test-2024-02-06-020832-ci-ln-l529zd2-latest   True        False         False      0s
```

**Comment by jsafrane** [comment]
/close
see https://issues.redhat.com/browse/OCPBUGS-28998 for a reason

**Pull request closed without merging**
