### PR TITLE
OCPBUGS-13386: Use csinode id feature

### PR DESCRIPTION
**Pull request by gnufied**
Fixes https://issues.redhat.com/browse/OCPBUGS-13386

### CODE REVIEW

**Comment by jsafrane** [comment]
@gnufied I don't like monitoring operator not starting.

```
            "message": "AttachVolume.Attach failed for volume \"pvc-142f44ce-6e20-4451-b1e0-7aa7e1bd5e72\" : rpc error: code = Internal desc = failed to find VirtualMachine for node:\"42053117-6b12-fe4e-82d2-dcd38f7382dd\". Error: csinodes.storage.k8s.io \"42053117-6b12-fe4e-82d2-dcd38f7382dd\" not found",
```

@mpt, monitoring it's our guinea pig that uses PVs and PVCs and it won't start if we break something on our side. Going to `Artifacts` and navigating through `artifacts/e2e-vsphere/gather-extra/artifacts/`, In `clusteroperators.json`, I can see `"monitoring"` is not happy there because a Pod `prometheus-k8s-1` has some issues:

```
                        "lastTransitionTime": "2023-05-26T01:25:41Z",
                        "message": "NoPodReady: shard 0: pod prometheus-k8s-0: containers with incomplete status: [init-config-reloader]\nshard 0: pod prometheus-k8s-1: containers with incomplete status: [init-config-reloader]",
                        "reason": "UpdatingPrometheusK8SFailed",
                        "status": "False",
                        "type": "Available"
```

And then I just look for `prometheus-k8s-1` in `events.json`. Accidentally (or luckily?), `prometheus-k8s-1` is both name of a pod and a PVC"

```
...
            "message": "waiting for first consumer to be created before binding",
...

            "message": "waiting for a volume to be created, either by external provisioner \"csi.vsphere.vmware.com\" or manually created by system administrator",
...
            "message": "External provisioner is provisioning volume for claim \"openshift-monitoring/prometheus-data-prometheus-k8s-1\"",
...
            "message": "Successfully provisioned volume pvc-142f44ce-6e20-4451-b1e0-7aa7e1bd5e72",
...
            "message": "Successfully assigned openshift-monitoring/prometheus-k8s-1 to ci-op-mx28hlh3-84b3d-4gdn9-worker-0-54xtg",
...
            "involvedObject": {
                "apiVersion": "v1",
                "kind": "Pod",
                "name": "prometheus-k8s-1",
                "namespace": "openshift-monitoring",
                "resourceVersion": "26091",
                "uid": "10b568ec-93b2-40e9-8033-5bcdb0352f16"
            },
            "kind": "Event",
            "lastTimestamp": "2023-05-26T01:21:20Z",
            "message": "AttachVolume.Attach failed for volume \"pvc-142f44ce-6e20-4451-b1e0-7aa7e1bd5e72\" : rpc error: code = Internal desc = failed to find VirtualMachine for node:\"4205452f-d61b-d63a-c3de-c641aa1f77b0\". Error: csinodes.storage.k8s.io \"4205452f-d61b-d63a-c3de-c641aa1f77b0\" not found",
```

Continuing with `gather-extra`, all interesting pods have logs in `pods/` dir. CSI driver ([openshift-cluster-csi-drivers_vmware-vsphere-csi-driver-controller-8446dfc9cd-8m6rt_csi-driver.log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_vmware-vsphere-csi-driver-operator/156/pull-ci-openshift-vmware-vsphere-csi-driver-operator-master-e2e-vsphere/1661887028192612352/artifacts/e2e-vsphere/gather-extra/artifacts/pods/openshift-cluster-csi-drivers_vmware-vsphere-csi-driver-controller-8446dfc9cd-8m6rt_csi-driver.log)) shows:

```
{"level":"info","time":"2023-05-26T01:20:44.312303598Z","caller":"vanilla/controller.go:2025","msg":"ControllerPublishVolume: called with args {VolumeId:d234105c-fbd5-4a20-9b69-e6b6df28fdf0 NodeId:4205f398-93fc-bac9-6dd8-4e6f71ad233a VolumeCapability:mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER >  Readonly:false Secrets:map[] VolumeContext:map[storage.kubernetes.io/csiProvisionerIdentity:1685063340526-7493-csi.vsphere.vmware.com type:vSphere CNS Block Volume] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}","TraceId":"8d1e7c1c-652e-47cc-8b06-c389d373288a"}
{"level":"info","time":"2023-05-26T01:20:44.312358783Z","caller":"node/manager.go:163","msg":"Empty nodeUUID observed in cache for the node: \"4205f398-93fc-bac9-6dd8-4e6f71ad233a\"","TraceId":"8d1e7c1c-652e-47cc-8b06-c389d373288a"}
{"level":"info","time":"2023-05-26T01:20:44.312374816Z","caller":"kubernetes/kubernetes.go:334","msg":"GetNodeUUID called for the node: \"4205f398-93fc-bac9-6dd8-4e6f71ad233a\" with useK8sCSINodeObj: true","TraceId":"8d1e7c1c-652e-47cc-8b06-c389d373288a"}
{"level":"error","time":"2023-05-26T01:20:44.317226418Z","caller":"kubernetes/kubernetes.go:348","msg":"failed to get K8s CSINode with the name: \"4205f398-93fc-bac9-6dd8-4e6f71ad233a\". Err: csinodes.storage.k8s.io \"4205f398-93fc-bac9-6dd8-4e6f71ad233a\" not found","TraceId":"8d1e7c1c-652e-47cc-8b06-c389d373288a",
...
```

`4205f398-93fc-bac9-6dd8-4e6f71ad233a` does not look like a name of a CSINode. We don't have CSINodes in gather-extra to confirm, you could check the full must-gather in `gather-must-gather` artifacts, but I don't think it's necessary - @gnufied should have enough info to start debugging.

**Comment by gnufied** [comment]
yeah we need to investigate this more thoroughly, I didn't expect it to go smoothly either and that was half of the reason I did not wanted this enabled last minute in 4.13.

**Comment by gnufied** [comment]
I think first we need - https://github.com/openshift/vmware-vsphere-csi-driver/pull/80 before we can merge this PR.

**Pull request merged**
