### PR TITLE
STOR-1593: Disable toplogy feature explicitly

### PR DESCRIPTION
**Pull request by gnufied**
fixes https://issues.redhat.com/browse/OCPBUGS-37455

### CODE REVIEW

**Comment by gnufied** [comment]
/payload-job periodic-ci-openshift-release-master-nightly-4.17-e2e-vsphere-ovn-csi

**Comment by gnufied** [comment]
While this fixes CSI volume provisioning issue. There are some other weirdness going on, which is causing specifically in-tree PVs to fail to delete with error:

```
2024-07-24T18:38:59.521133288Z vanilla/controller.go:2092 failed to get VolumeID from volumeMigrationService for volumePath: "[vsanDatastore-2] be583566-a662-6970-2903-3cfdfe8f21e0/_006c/_005a/c01a7c7317a24e0b934b5c233dfad560.vmdk"
sigs.k8s.io/vsphere-csi-driver/v3/pkg/csi/service/vanilla.(*controller).DeleteVolume.func1
        /go/src/github.com/kubernetes-sigs/vsphere-csi-driver/pkg/csi/service/vanilla/controller.go:2092
sigs.k8s.io/vsphere-csi-driver/v3/pkg/csi/service/vanilla.(*controller).DeleteVolume
        /go/src/github.com/kubernetes-sigs/vsphere-csi-driver/pkg/csi/service/vanilla/controller.go:2166
github.com/container-storage-interface/spec/lib/go/csi._Controller_DeleteVolume_Handler
        /go/src/github.com/kubernetes-sigs/vsphere-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:6598
google.golang.org/grpc.(*Server).processUnaryRPC
        /go/src/github.com/kubernetes-sigs/vsphere-csi-driver/vendor/google.golang.org/grpc/server.go:1372
google.golang.org/grpc.(*Server).handleStream
        /go/src/github.com/kubernetes-sigs/vsphere-csi-driver/vendor/google.golang.org/grpc/server.go:1783
google.golang.org/grpc.(*Server).serveStreams.func2.1
        /go/src/github.com/kubernetes-sigs/vsphere-csi-driver/vendor/google.golang.org/grpc/server.go:1016
2024-07-24T18:3
```

**Comment by jsafrane** [comment]
/retitle Disable toplogy feature explicitly

I'm un-linking this PR from OCPBUGS-37455 - we fixed that bug by reverting external-provisioner rebase.

**Comment by jsafrane** [comment]
/reopen

It is still needed by the new external-provisioner. https://github.com/openshift/csi-external-provisioner/pull/104 fails because of topology.

**Pull request merged**
