### PR TITLE
Bug 2072139: Create separate controller and node roles

### PR DESCRIPTION
**Pull request by jsafrane**
Create a separate Role + ClusterRole + their Bindings for the node ServiceAccount.

~And remove `privileged` role from the controller.~

Reuse `vmware-vsphere-csi-driver-role` / `vmware-vsphere-csi-driver-binding` for the controller ServiceAccount. I am not renaming the object to make sure we do not leak unused ClusterRole/Binding during update.

I used upstream node Role and ClusterRole from
https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/v2.5.1/manifests/vanilla/vsphere-csi-driver.yaml.
`

### CODE REVIEW

**Comment by jsafrane** [comment]
/hold
I still need to review if the controller needs to run privileged pods, it looks suspicious

**Comment by jsafrane** [comment]
cc @openshift/storage

**Review by bertinatto — COMMENTED** [review]
/lgmt

**Pull request merged**
