### PR TITLE
Bug 2105334: Reorder static resources to create RBAC first

### PR DESCRIPTION
**Pull request by gnufied**
The privileged RBAC objects should be created first to make sure the CSI
driver Deployment / DaemonSet can use privileged SCC.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2105334

### CODE REVIEW

**Comment by dcbw** [comment]
same `Failed while waiting on imagestream import`
/retest-required

**Comment by dcbw** [comment]
/retest-required
failed due to https://github.com/openshift/release/pull/30367

**Comment by jsafrane** [comment]
Resize test errors are tracked in https://bugzilla.redhat.com/show_bug.cgi?id=2107140
/override ci/prow/e2e-vsphere-csi

**Pull request merged**
