### PR TITLE
STOR-1128: Change the default SC to the CSI one

### PR DESCRIPTION
**Pull request by bertinatto**
CC @openshift/storage

### CODE REVIEW

**Comment by bertinatto** [comment]
I tested this with https://github.com/openshift/cluster-storage-operator/pull/332 and the default StorageClass was:

1. **thin** when upgraded from 4.12
2. **thin-csi** on a new cluster

**Comment by bertinatto** [comment]
/hold
I need to remove the vendor changes once https://github.com/openshift/library-go/pull/1459 merges. Also, need to wait for the rebase.

**Comment by bertinatto** [comment]
/assign @dobsonj 
Who recently touched this code.

**Comment by gnufied** [comment]
Can you also pull for https://github.com/openshift/library-go/pull/1460 ? So as we can get CVE fixed too?

**Comment by bertinatto** [comment]
> Can you also pull for [openshift/library-go#1460](https://github.com/openshift/library-go/pull/1460) ? So as we can get CVE fixed too?

Pulled in https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/136.

**Comment by bertinatto** [comment]
> /hold I need to remove the vendor changes once [openshift/library-go#1459](https://github.com/openshift/library-go/pull/1459) merges. Also, need to wait for the 1.26 kube rebase.

/hold cancel

**Comment by dobsonj** [comment]
Just `[sig-arch][Late] operators should not create watch channels very often [apigroup:config.openshift.io] [Suite:openshift/conformance/parallel]`
/retest-required

**Comment by ropatil010** [comment]
/retest-required

Results added here: https://issues.redhat.com/browse/STOR-1153 
1. On fresh cluster default sc has been moved to CSI.
2. 4.12 to PR fix cluster the default sc will be still intree provisioner

Additional tests updated in above mentioned link. 
/label qe-approved

**Comment by bertinatto** [comment]
/override ci/prow/e2e-vsphere-csi-migration

This job is no longer required.

**Pull request merged**
