### PR TITLE
OCPBUGS-24716:  Enable new features to prevent CSI driver from crash looping (revert OCPBUGS-23970)

### PR DESCRIPTION
**Pull request by gnufied**
Reverts openshift/vmware-vsphere-csi-driver-operator#192

### CODE REVIEW

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by jsafrane** [comment]
/hold cancel
/override ci/prow/e2e-vsphere-ovn-upgrade
because of https://issues.redhat.com/browse/OCPBUGS-25431

**Pull request merged**
