### PR TITLE
[release-4.14] OCPBUGS-28988: Mark the operator as Disabled on connection error

### PR DESCRIPTION
**Pull request by jsafrane**
This is a manual cherry-pick of https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/219 into 4.14.

cc @openshift/storage

### CODE REVIEW

**Comment by Phaow** [comment]
/label cherry-pick-approved
/label qe-approved
With the **[bug reproduce steps](https://issues.redhat.com/browse/OCPBUGS-27159?focusedId=23787718&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23787718)**, using the pre merged build, the same reproduce step the issue doesn't happen again, 
pre verify passed on `4.14.0-0.test-2024-02-06-013536-ci-ln-1chqt4b-latest` (`build 4.14,openshift/vmware-vsphere-csi-driver-operator#223,openshift/cluster-storage-operator#449`)
```console
[pewang@preserve-storage-server1 ~]$ oc get co/storage
NAME      VERSION                                                AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
storage   4.14.0-0.test-2024-02-06-013536-ci-ln-1chqt4b-latest   False       True          False      4s      VSphereCSIDriverOperatorCRAvailable: Waiting for VSphere operator to report status
[pewang@preserve-storage-server1 ~]$ oc get co/storage -w
NAME      VERSION                                                AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
storage   4.14.0-0.test-2024-02-06-013536-ci-ln-1chqt4b-latest   True        False         False      3s
```

**Comment by duanwei33** [comment]
@jsafrane Hi, seems we miss a "lgtm" to merge it.

**Comment by jsafrane** [comment]
/close 
See https://issues.redhat.com//browse/OCPBUGS-28988 for a reason.

**Pull request closed without merging**
