### PR TITLE
Deploy webhook

### PR DESCRIPTION
**Pull request by bertinatto**
This reverts commit 65a00acc38e03cdb4ff686500ae2f9190b2012c8. 

CSI migration is already enabled by default in the driver (see https://github.com/openshift/vmware-vsphere-csi-driver-operator/pull/48) , so now we should be able to deploy the webhook without issues.

CC @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
> event happened 513 times, something is wrong: ns/openshift-cluster-csi-drivers deployment/vmware-vsphere-csi-driver-operator - reason/ValidatingWebhookConfigurationUpdated Updated ValidatingWebhookConfiguration.admissionregistration.k8s.io/validation.csi.vsphere.vmware.com because it changed

**Comment by gnufied** [comment]
@bertinatto indeed something is wrong with this PR:

```
event happened 215 times, something is wrong: ns/openshift-cluster-csi-drivers deployment/vmware-vsphere-csi-driver-operator - reason/ValidatingWebhookConfigurationUpdated Updated ValidatingWebhookConfiguration.admissionregistration.k8s.io/validation.csi.vsphere.vmware.com because it changed
```

**Comment by bertinatto** [comment]
> @bertinatto indeed something is wrong with this PR:
> 
> ```
> event happened 215 times, something is wrong: ns/openshift-cluster-csi-drivers deployment/vmware-vsphere-csi-driver-operator - reason/ValidatingWebhookConfigurationUpdated Updated ValidatingWebhookConfiguration.admissionregistration.k8s.io/validation.csi.vsphere.vmware.com because it changed
> ```

@gnufied the library-go function that applies this object isn't very clever (as it always update the object). That's the reason of the multiple Update events. We need to fix that before merging this PR.

**Comment by dobsonj** [comment]
> /lgtm cancel

^ this didn't remove the label for some reason
/hold
until Hemant and Fabio are ready

**Comment by bertinatto** [comment]
This PR depends on a fix for this: https://github.com/openshift/library-go/pull/1129#discussion_r669819849.

I started a discussion here: https://github.com/openshift/library-go/pull/1256

**Comment by bertinatto** [comment]
/hold cancel
https://github.com/openshift/library-go/pull/1256 has been merged and the multiple-update-events issue is gone.

**Pull request merged**
