### PR TITLE
Bug 1949554: vSphere: Add metrics scraping

### PR DESCRIPTION
**Pull request by jsafrane**
Configure Prometheus to collect vSphere CSI driver sidecar metrics. The driver itself does not emit any metrics.
Background:

* add parameter to each sidecar to run HTTP endpoint on localhost with metrics.
* for each sidecar, add kube-rbac-proxy, which opens HTTPS endpoint on the pod and proxies it to the HTTP metric on loopback (goal: get HTTPS for metrics, we don't like HTTP).
* create Service and ServiceMonitor to scrape the HTTPS endpoins.

WIP: waiting for openshift/library-go#1050

### CODE REVIEW

**Comment by jsafrane** [comment]
we need https://github.com/openshift/cluster-storage-operator/pull/154 merged first

**Comment by jsafrane** [comment]
Finally! I got the metrics:
```
count by(container) (rate(csi_sidecar_operations_seconds_count[1d]))

  | attacher-kube-rbac-proxy | 4
  | provisioner-kube-rbac-proxy | 4
  | resizer-kube-rbac-proxy | 4
```

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
